  import type { Metadata } from "next";
  import { Geist, Geist_Mono, Oswald, } from "next/font/google";
  import "./globals.css";
  import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { PlanProvider } from "@/context/PlanContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

  const oswald = Oswald({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
  });

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Fit Log",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className={`${oswald.className} min-h-full flex flex-col bg-[#0C0D10]`}>
          <PlanProvider>
            <Navbar />
            <main>
              {children}      
            </main>
            <Footer />
          </PlanProvider>       
          <ToastContainer className={`z-99999`} />
        </body>
      </html>
    );
  }
