  import type { Metadata } from "next";
  import { Geist, Geist_Mono, Oswald, } from "next/font/google";
  import "./globals.css";
  import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

  const oswald = Oswald({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
  });

  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
      <html
        data-theme="dark"
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
        <body className={`${oswald.className} min-h-full flex flex-col`}>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </body>
      </html>
    );
  }
